[package]
name = "haar_lib"
version = "0.1.0"
authors = ["Haar"]
edition = "2018"

[dependencies]
rand = { version = "=0.8.5" }

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "katex.html",
]